### ISSUE TITLE
Which SMTP server shall we use for e-mail notifications?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#12]
Currently OpenScanHub supports SMTP server that is running on the same host as the [hub](https://github.com/openscanhub/openscanhub/blob/bd99e35381a62c08217b93782efa2e324bc603bd/osh/hub/scan/notify.py#L104). This issue tracks getting a recommendation from the Fedora infrastructure team about which e-mail server to use and getting access or creating a new one for OpenScanHub deployments.

**Comment by siteshwar** [comment]
It should be `bastion01.iad2.fedoraproject.org` inside the OpenShift cluster.

**Comment by praiskup** [comment]
Can msmtp be an option? https://wiki.alpinelinux.org/wiki/Relay_email_to_gmail_(msmtp,_mailx,_sendmail

**Comment by siteshwar** [comment]
@nirik @zlopez Can you point me to how other Fedora services configure the mailing infrastructure?

**Comment by siteshwar** [comment]
It would also require a change in [this line](https://github.com/openscanhub/openscanhub/blob/f5ccf9619c07586f1c0b6ba8cdcc5b0ba81a3805/osh/hub/scan/notify.py#L60), as the e-mail field is not autogenerated.

**Comment by siteshwar** [comment]
I plan to use `postfix` as the SMTP server, as we use the same internally. Let me know if anybody has an objection to that.

**Comment by siteshwar** [comment]
@nirik @zlopez Can you provide me the exact configurations for the SMTP server used by the Fedora infrastructure?

**Comment by siteshwar** [comment]
It turns out that we do not need a SMTP server on the container, as we use django for sending e-mails. We can directly use the fedora-infra SMTP server:

https://pagure.io/fedora-infra/ansible/pull-request/1932#request_diff

**Comment by siteshwar** [comment]
This was fixed by using the [bastion](https://pagure.io/fedora-infra/ansible/pull-request/1932) e-mail server provided by the Fedora infrastrucutre. Example [reply](https://lists.fedoraproject.org/archives/list/openscanhub@lists.fedoraproject.org/thread/5YNCSQV5ZWBCHTL22V5SBJQLLLCTILF2/) to the notifications.
