### ISSUE TITLE
Which e-mail addresses shall we use for notifications?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#2]
OpenScanHub uses e-mail addresses for 2 types of notifications:

- `From` and `reply-to`  field for notifications that are generated for users for who submitted a scan.
- Notifications for developers/admins of the deployment for failed task notifications etc.

This issue tracks creating new or reusing existing e-mail addresses for notifications.

**Comment by siteshwar** [comment]
As per my understanding, we need to have 3 different mailing lists:

- openscanhub-users@lists.fedoraproject.org - For the users of the project. This would be used in `from` and `reply-to` fields in the notification e-mails. Users can reply to the scan notifications and ask questions about results, scan failures etc.
- openscanhub-devel@lists.fedoraproject.org - For the developers of the Fedora OpenScanHub staging and production instance. This list should have people from upstream GitHub repository.
- openscanhub-admins@lists.fedoraproject.org - For the administrators who maintain the staging and production deployments. It could be used in case there is an outage, certificate expiry etc. This list may overlap with the `devel` list, but may not be the same. People from the fedora-infra team should be on this list.


@kdudka @nirik @Zlopez @darknao Comments?

**Comment by Zlopez** [comment]
I'm not sure if we need three mailing lists for one project, @siteshwar do you expect high traffic on those lists?

**Comment by siteshwar** [comment]
> I'm not sure if we need three mailing lists for one project, @siteshwar do you expect high traffic on those lists?

For users of the project, I would expect the traffic to grow over time as there would always be questions from the community about build/scan failures or in general. We definitely need something dedicated to the users.

For the upstream developers of the project, we currently do not have a public list.  So it would be good to have. Also, this list would get notifications about scan failures. So the upstream developers could debug them.

For the admins of the projects, I am fine with using something existing used by the fedora-infra people. But if its common, then its very likely I would have to find a way ignore most of the traffic on that list.

**Comment by kdudka** [comment]
@siteshwar I am not sure about `openscanhub-devel`.  Most of the devel-related discussion happens on GitHub already.

**Comment by siteshwar** [comment]
> @siteshwar I am not sure about `openscanhub-devel`. Most of the devel-related discussion happens on GitHub already.

Internally, `openscanhub-devel` is used to send notifcations regarding scan failures. Where should that go?

**Comment by siteshwar** [comment]
> @siteshwar Do you expect anyone to subscribe a list to be notified about failed scans submitted by other users/services? Note that failed tasks can also be displayed in the web UI now: https://openscanhub.stg.fedoraproject.org/task/failed/

Ok, my impression was that you actively follow up on the failed scans reported through internal `openscanhub-devel` list. If thats not the case [this setting](https://github.com/openscanhub/openscanhub/blob/f5ccf9619c07586f1c0b6ba8cdcc5b0ba81a3805/osh/hub/settings_local.py#L131) is useless. Shall this be set to empty string in the Fedora deployments?

**Comment by kdudka** [comment]
For the internal OSH instance we have a team that monitors failed scans and create Jira issues for common causes of scan failures.  I do not think this would work for the Fedora instance.  If you want to set an empty string or `None`, some tiny code changes might be needed to handle the value accordingly.

**Comment by siteshwar** [comment]
> For users of the project, I would expect the traffic to grow over time as there would always be questions from the community about build/scan failures or in general. We definitely need something dedicated to the users.

We need to make it clear in the footer of the e-mail notifications that users can reply to the e-mails to ask questions about scans. Other idea is to have a matrix channel (may be `#openscanhub` or `#openscanhub-users`).

**Comment by siteshwar** [comment]
So, it turns out that the internal and external use cases may be different. This is my idea right now:

- We should have a single `openscanhub@fedoraproject.org` mailing list for all OpenScanHub related discussions.
- We should have a matrix channel `#openscanhub` for publicly discussing issues.

**Comment by kdudka** [comment]
As discussed privately, I would subscribe the `openscanhub@lists.fedoraproject.org` mailing list but I do not use Matrix myself and do not feel like starting with Matrix just because of this.

**Comment by siteshwar** [comment]
https://pagure.io/fedora-infrastructure/issue/11866

**Comment by siteshwar** [comment]
The list now lives on: https://lists.fedoraproject.org/archives/list/openscanhub@lists.fedoraproject.org/

I am going to close this issue and would open another issue to follow up on Matrix (or any other) channel for communication through chat.
