### ISSUE TITLE
Set up fedora messaging configurations

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#3]
OpenScanHub supports sending notifications through UMB. This issue tracks setting up UMB configurations for the Fedora infrastructure.

EDIT: Modified title to reflect that we should use fedora messaging configurations directly.

**Comment by kdudka** [comment]
OpenScanHub does not send any messages to UMB for scans triggered by `osh-cli`.  Are you going to use the interface for integration with Errata Tool in the public deployment?  If not, there is no point in configuring UMB.

**Comment by nirik** [comment]
Just FYI, fedora has it's own message bus. It's usually interacted with via: https://github.com/fedora-infra/fedora-messaging
(It's a rabbitmq/AMQP cluster with some schemas on top).

**Comment by siteshwar** [comment]
OpenScanHub does not support rabbitmq in upstream.

We may have to use polling for task logs/state through `osh-cli` command for PackIt integration.

**Comment by lachmanfrantisek** [comment]
I hope implementing result/status reporting to Fedora-messaging might be easier than implementing polling in Packit.

**Comment by siteshwar** [comment]
https://pagure.io/fedora-infrastructure/issue/11853

**Comment by siteshwar** [comment]
For my own reference:

Messages Packit listens https://github.com/packit/deployment/blob/ac1dd10bc2be07c1d7b20825aab871e08490d254/secrets/packit/prod/fedora.toml.j2#L49

Fedora messaging consumer for Packit Service https://github.com/packit/packit-service-fedmsg

Callbacks https://github.com/packit/packit-service-fedmsg/blob/main/packit_service_fedmsg/callbacks.py

Thanks @lbarcziova  for the links!
