### ISSUE TITLE
Shall we have a Matrix channel for OpenScanHub?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#30]
This issue tracks creating (or reusing any other existing) channel for discussions related to OpenScanHub on https://chat.fedoraproject.org/.

**Comment by nirik** [comment]
I think in general discussion of this would be welcome in #devel:fedoraproject.org... if there turns out to be too much traffic a seperate channel could be created at that point.

**Comment by siteshwar** [comment]
I am closing this issue as it has become stale. We should bring this topic again in the future, if a community member requests for channel to get support through chat.
