### ISSUE TITLE
Where should the user documentation go?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#34]
This issue tracks documenting OpenScanHub for users of the Fedora project.

@nirik Shall the user documentation go to [Fedora wiki](https://fedoraproject.org/wiki/Fedora_Project_Wiki)?

This issue was previously discussed with @kdudka and we wanted to use something that could be tracked through `git`. However, we would appreciate any guidelines from the Fedora infrastructure team.

**Comment by nirik** [comment]
You could use the wiki, thats easy, but yes, no got backing. 

You could use docs.fedoraproject.org, but I am not sure where on there. The various teams/parts are built from different git repos. Perhaps a seperate thing along the lines of the defensive coding guide: https://docs.fedoraproject.org/en-US/defensive-coding/ ?

**Comment by siteshwar** [comment]
@nirik @kdudka  I would start drafting user documentation on the Fedora wiki and see how things go. Let me know if you could recommend me any template to follow.

**Comment by siteshwar** [comment]
I made an initial draft of the documentation at: https://fedoraproject.org/wiki/OpenScanHub

**Comment by siteshwar** [comment]
There is always a room for improvement in the docs, but we have agreed to do it on the Fedora wiki and the basic documentation is done. So, I am going to close this issue.
