### ISSUE TITLE
Get SSL certificates for staging and production deployment

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#4]
This issue tracks getting SSL certificates for staging and production deployment.

**Comment by nirik** [comment]
Note that fedora openshift clusters are being our proxy network and tls is terminated there, so no need for certs on the openshift side of things. 
When a new site is added to our proxies we usually configure letsencrypt to just get a cert for it. In the case of *.fedoraproject.org and *.stg.fedoraproject.org sites, our proxies have wildcard certs for those for any applications using them. 
So, for fedorainfracloud we can use letsencrypt, and for fedoraproject.org we can just use the wildcard cert. :)

**Comment by siteshwar** [comment]
The SSL certificates are [automatically generated](https://github.com/sclorg/httpd-container/blob/6c539555703e90e5792436094a341503df88d2d4/2.4/root/usr/share/container-scripts/httpd/common.sh#L15) in the httpd container. So I am closing this issue.

@nirik But thanks for the pointers!
