### ISSUE TITLE
Set up Copr repository for production `osh-worker` RPMs

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#42]
We deploy RPMs in `devel` Copr repository in the staging environment. This issue tracks setting up a Copr repository for `osh-worker` RPMs that should be deployed in the production.

**Comment by siteshwar** [comment]
@praiskup We have `devel` RPMs in [Fedora Copr](https://copr.fedorainfracloud.org/coprs/g/openscanhub/devel/). How can we move an existing RPM to a production repository?

**Comment by praiskup** [comment]
You can use the "forking" feature (it copy-pastes and re-signs the RPMs, even into an existing project).

But I'd again suggest you to use the official Fedora Infra repos:

https://kojipkgs.fedoraproject.org/repos-dist/f39-infra-stg/
https://kojipkgs.fedoraproject.org/repos-dist/f39-infra/
https://kojipkgs.fedoraproject.org/repos-dist/f38-infra-stg/
....

**Comment by siteshwar** [comment]
@praiskup OpenScanHub is not officially a Fedora service yet. So I do not think I would be allowed to use that. I might just stick to fork to a "production" repository.

@kdudka Any comments on it?

**Comment by praiskup** [comment]
> So I do not think I would be allowed to use that.

This used to be the other way around before actually :) in Fedora Infra, we were only allowed to install software from Infra repos.

**Comment by kdudka** [comment]
@siteshwar I have no experience with maintaining Fedora services.  So I will refrain from commenting on this.

**Comment by siteshwar** [comment]
> > So I do not think I would be allowed to use that.
> 
> This used to be the other way around before actually :) in Fedora Infra, we were only allowed to install software from Infra repos.

@nirik I would appreciate any comments on this.

**Comment by nirik** [comment]
Yes, in the past the policy was all production things were built in koji. That somewhat predates openshift however, as we now have apps that install from git repos, build elsewhere, etc. 

So, I think for this service that you are maintaining, a copr repo would be ok. 

koji infra tags is likely a lot of overhead for you right now, especially if you have a number of deps.

**Comment by siteshwar** [comment]
In the future, we should automated the second step, and have a `production-ready` repository. However, move to `production` repository should be done manually.

**Comment by siteshwar** [comment]
I am closing this issue as I would follow up on the documentation in https://github.com/openscanhub/fedora-infra/issues/26.
