### ISSUE TITLE
Run differential scans on the Fedora critical path packages

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#50]
This issue tracks running differential scans on the [Critical path package](https://fedoraproject.org/wiki/Critical_path_package) list and collecting results that may be useful.

**Comment by siteshwar** [comment]
I ran a differential scan between packages tagged with f41 and f40, and here are the packages which are reported to have introduced new defects:


https://openscanhub.stg.fedoraproject.org/task/1423/log/added.html                                                                                                                                                                          
                                                           
https://openscanhub.stg.fedoraproject.org/task/1427/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1429/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1430/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1433/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1438/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1450/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1451/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1456/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1479/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1486/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1495/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1500/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1503/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1508/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1515/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1521/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1526/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1545/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1554/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1562/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1563/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1564/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1570/log/added.html

https://openscanhub.stg.fedoraproject.org/task/1572/log/added.html

**Comment by nirik** [comment]
This is a great idea. ;) It might work well for a devel list/discussion post? 

would need to add package names and maintainer names so people could search for their packages.

**Comment by siteshwar** [comment]
> This is a great idea. ;) It might work well for a devel list/discussion post?

@nirik For now I just did a test scan. I would probably follow up with the community through #53.

> 
> would need to add package names and maintainer names so people could search for their packages.

**Comment by nirik** [comment]
Yeah, makes sense.

**Comment by siteshwar** [comment]
I tried to summarize the report for packages changed in F41 at https://svashisht.fedorapeople.org/f41/index.html. I plan to share something similar with the community in near future.

**Comment by nirik** [comment]
Looks nice. :) Will be interesting to see what people take from it/fix based on it.
