### ISSUE TITLE
Set up integration with Packit

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#54]
This issue tracks integration with the [PackIt](https://packit.dev/) service. Possible [blocker](https://pagure.io/fedora-infrastructure/issue/11853#comment-903167) has been discussed [earlier](https://github.com/openscanhub/fedora-infra/issues/3#issuecomment-2018402910).

@lachmanfrantisek @lbarcziova Please leave your comments, if I missed anything.

EDIT: [Related issue](https://github.com/packit/packit-service/issues/2107) in PackIt upstream.

**Comment by kdudka** [comment]
@siteshwar If I remember correctly, there was a request from by PackIt team on the last two quarterly meetings to make `osh-cli` accept SRPMs specified by URLs.  I think the initial implementation should be pretty simple but I am not sure if we track this anywhere.

**Comment by siteshwar** [comment]
@kdudka It is tracked through https://github.com/openscanhub/openscanhub/issues/248.

**Comment by siteshwar** [comment]
I discussed this issue with @lachmanfrantisek today and we agreed to introduce a `packit build in-osh` subcommand. Its implementation should look like:

- `packit build in-osh`: Perform a full scan (`osh-cli mock-build`) on the project.
- `packit build in-osh --srpm-version-diff second.srpm`: Perform a differential build (`osh-cli version-diff-build`) with the second srpm.

We managed to hack together a basic prototype of the CLI command. But it needs to be polished before a pull request can be opened against upstream.

**Comment by kdudka** [comment]
Thank you for working on this!  My proposal is to give the subcommand a more self-explaining name, such as `scan-in-osh`.  Otherwise this may arouse an impression that OSH is a build service.

**Comment by siteshwar** [comment]
> Thank you for working on this! My proposal is to give the subcommand a more self-explaining name, such as `scan-in-osh`. Otherwise this may arouse an impression that OSH is a build service.

@kdudka `packit ` has `build` subcommand, but not `scan`. So, for copr the command looks like `packit build in-copr`.

@lachmanfrantisek Do you think we can introduce a `scan` subcommand? This may be useful if you plan to integrate with other scanners in the future.

**Comment by lachmanfrantisek** [comment]
Hmm, we don't have any other scanning integration planned now. Since it actually performs a build during the OSH scan, I would probably leave it as is for now... We can definitely change this or make an alias if we realise this was a bad idea. But with Packit, the CLI is not too important compared to the service.

**Comment by kdudka** [comment]
My proposal was not to replace `build` but to replace `in-osh` with `scan-in-osh` (or perhaps `scan-with-osh`?), which I thought would be trivial.  But keeping the current name is also fine.

**Comment by siteshwar** [comment]
This issue should be followed up by the Packit team through https://github.com/packit/packit-service/issues/2107 and https://github.com/packit/packit-service/issues/2454.

I am closing it, as there is nothing to be done from OSH side.
