### ISSUE TITLE
Enable find-unicode-control

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#63]
find-unicode-control is currently disabled in production and may require some extra work before being enabled. This issue tracks enabling find-unicode-control in production.

**Comment by siteshwar** [comment]
@kdudka Currently the `default` scan profile has this value set:

```{"analyzers": "gcc,cppcheck,shellcheck", "csmock_args": "--gcc-analyze", "koji_profile": "koji"}```

 Shall I add `unicontrol` in the analyzers? Do I need to add anything else in the `csmock_args`?

**Comment by kdudka** [comment]
I would suggest to add also `--unicontrol-notests --unicontrol-bidi-only`, which is used by the internal OSH instance since we enabled `unicontrol`.

**Comment by siteshwar** [comment]
It has been enabled in production. Test scan: https://openscanhub.fedoraproject.org/task/4095/
