### ISSUE TITLE
Enable Clippy

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#64]
This issue tracks enabling Clippy in production.

**Comment by siteshwar** [comment]
@kdudka Would it be sufficient to add `clippy` in the `default` scan profile and install `csmock-plugins-clippy` on the workers?

**Comment by kdudka** [comment]
Yes, it should be harmless for packages that do not build any Rust code.  We will see how it will work with Rust packages that have not yet been scanned in RHEL yet...

**Comment by siteshwar** [comment]
It has been enabled in production. Test scan: https://openscanhub.fedoraproject.org/task/4310/
