### ISSUE TITLE
Set up logging policy

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#7]
This issue tracks setting up a logging policy and getting access to log01 (central syslog host). We should also consider getting access to Red Hat splunk instance.

**Comment by siteshwar** [comment]
https://pagure.io/fedora-infrastructure/issue/11865

**Comment by siteshwar** [comment]
@nirik I can access the central syslog host, but there is no entry for OpenScanHub under `/var/log/hosts/`. Do we need to add it somewhere else?

**Comment by nirik** [comment]
Yes, thats expected on the syslog side. The openshift cluster just sends all apps logs out, but they are coming from each compute node. 

Those nodes have hostnames: workerNN.ocp.iad.fedoraproject.org (prod) and workerNN.ocp.stg.iad2.fedoraproject.org for staging. If you know what compute node your pod is on (by using say 'oc get pods -o wide') you can just drill down under that node. If you don't know you will need to search all the nodes.

**Comment by siteshwar** [comment]
@nirik Can you point me to the documentation about how to get access to the Red Hat splunk instance?

**Comment by nirik** [comment]
Sure. Info sent internally... let me know if that doesn't work

**Comment by siteshwar** [comment]
Unfortunately, it seems the Splunk instance is only accessible to the Red Hat employees. I have opened a request for it internally and would close this issue.
