### ISSUE TITLE
Set backing up policy for `/var/lib/osh`

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/fedora-infra#8]
`/var/lib/osh` path contains results generated for each scan. This issue tracks creating a back up policy for `/var/lib/osh` path.

**Comment by siteshwar** [comment]
@nirik Here are a few questions:

- How the backups should be triggered?
- Where they should be stored?
- How long they should be kept?

**Comment by siteshwar** [comment]
> So, I'd say it's up to you... unless you don't want to deal with them and would like us to come up with a setup to do backups of these things.

I would prefer to use the backup processes/policies used by the Fedora infrastrcuture team. Do I have to open a separate issue to get access to NFS? I do not want to take care of the backups separately and would prefer something maintained by the infra team.

@kdudka As I understand, we use NFS internally and should not have problems with the Fedora deployment.

**Comment by kdudka** [comment]
@siteshwar The internal OSH instance uses a local storage but we plan to migrate it to a remote externally managed storage in the near future.  I do not think that OSH has very specific requirements for the `/var/lib/osh` storage.

**Comment by siteshwar** [comment]
https://pagure.io/fedora-infrastructure/issue/11852

**Comment by siteshwar** [comment]
This issue can be closed as the backups would be handled by the fedora-infra team.
